### ISSUE TITLE
rADMGdist() 

### ISSUE THREAD

**Issue by zhongyi960403** [rje42/ADMGs2#5] opened 2021-02-01 22:22 UTC
For some graphs G，  rADMGdist(G) stucks and cannot produce output
```
G <- graphCr("2 -> 5 <-> 3 <-> 4","5 <-> 1 <-> 2")
rADMGdist(G,dims = rep(2,n),r=FALSE)
```
This is just an random example and it happens very often if you generate graph from rADMG().

**Comment by rje42** [comment] 2021-02-02 11:15
Hmm, the problem is that the parameters are variation dependent, but being generated separately, so most combinations get rejected.  I will see what I can do as a quick fix.

**Comment by rje42** [comment] 2021-02-02 14:01
OK, I think this is now fixed, though I've had to completely change the way the function generates distributions.

**Closed as completed by rje42** 2021-02-02 14:01 UTC
